# Generated by Django 4.0.1 on 2022-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('feedback', models.TextField()),
                ('feeddate', models.DateField(auto_now_add=True)),
                ('username', models.TextField()),
            ],
        ),
    ]
